import type {
  CloudComputeValues,
  EnergyValues,
  GeneralValues,
  GpuValues,
  HumanResourcesValues,
  NetworkingValues,
  OnPremComputeValues,
  SecurityComplianceValues,
  SoftwareValues,
  StorageValues,
} from '@/lib/types'
import type { CostFormValues } from '../types'

export const generalDefaults: GeneralValues = {
  analysisPeriod: 5,
  inflationRate: 3.0,
  calculationMode: 'tco',
  enableSensitivityAnalysis: true,
  sensitivityVariable: undefined,
  sensitivityRangePercent: 20,
}

export const onPremComputeDefaults: OnPremComputeValues = {
  useOnPremCpu: true,
  onPremCpuQuantity: 4,
  onPremCpuUnitCost: 2500,
  onPremCpuSalvageValue: 10,
  useOnPremMotherboard: true,
  onPremMotherboardQuantity: 4,
  onPremMotherboardUnitCost: 800,
  onPremMotherboardSalvageValue: 10,
  useOnPremMemory: true,
  onPremMemoryCapacityGb: 512,
  onPremMemoryCostPerGb: 8,
  onPremMemorySalvageValue: 10,
  useOnPremChassis: true,
  onPremChassisQuantity: 2,
  onPremChassisUnitCost: 3000,
  onPremChassisSalvageValue: 10,
  useOnPremRacks: true,
  onPremRacksQuantity: 1,
  onPremRacksUnitCost: 2000,
  onPremRacksSalvageValue: 10,
}

export const cloudComputeDefaults: CloudComputeValues = {
  useCloudGeneralVm: true,
  cloudGeneralVmCount: 8,
  cloudGeneralVmHourlyRate: 0.15,
  cloudGeneralVmHoursPerMonth: 730,
  useCloudComputeVm: true,
  cloudComputeVmCount: 4,
  cloudComputeVmHourlyRate: 0.25,
  cloudComputeVmHoursPerMonth: 730,
  useCloudMemoryVm: true,
  cloudMemoryVmCount: 2,
  cloudMemoryVmHourlyRate: 0.35,
  cloudMemoryVmHoursPerMonth: 730,
  useCloudStorageVm: false,
  cloudStorageVmCount: 0,
  cloudStorageVmHourlyRate: 0,
  cloudStorageVmHoursPerMonth: 0,
}

export const energyDefaults: EnergyValues = {
  useOnPremPowerConsumption: true,
  onPremPowerRating: 2400,
  onPremLoadFactor: 70,
  onPremElectricityCost: 0.14,
  useOnPremUps: false,
  onPremUpsUnitCost: 0,
  onPremUpsQuantity: 0,
  onPremUpsBatteryFailureRate: 0,
  onPremUpsBatteryReplacementCost: 0,
  useOnPremGenerator: false,
  onPremGeneratorUnitCost: 0,
  onPremGeneratorQuantity: 0,
  onPremGeneratorFuelConsumptionRate: 0,
  onPremGeneratorFuelUnitCost: 0,
  onPremGeneratorAnnualUsageHours: 0,
  useOnPremHvac: false,
  onPremHvacUnitCost: 0,
  onPremHvacQuantity: 0,
  onPremHvacPowerConsumption: 0,
  onPremHvacLoadFactor: 0,
  onPremHvacTechnicianHourlyRate: 0,
  onPremHvacHoursWorked: 0,
  useOnPremColocation: true,
  onPremColocationMonthlyCost: 1500,
  onPremColocationAnnualIncrease: 3,
}

export const gpuDefaults: GpuValues = {
  useOnPremTrainingGpu: true,
  onPremTrainingGpuQuantity: 4,
  onPremTrainingGpuUnitCost: 15000,
  useOnPremInferenceGpu: true,
  onPremInferenceGpuQuantity: 8,
  onPremInferenceGpuUnitCost: 5000,
  useCloudTrainingGpu: true,
  cloudTrainingGpuCount: 4,
  cloudTrainingGpuHourlyRate: 3.5,
  cloudTrainingGpuHoursPerMonth: 730,
  useCloudInferenceGpu: true,
  cloudInferenceGpuCount: 8,
  cloudInferenceGpuHourlyRate: 0.65,
  cloudInferenceGpuHoursPerMonth: 730,
}

export const humanResourcesDefaults: HumanResourcesValues = {
  useOnPremSysAdmin: true,
  onPremSysAdminCount: 2,
  onPremSysAdminSalary: 125000,
  onPremSysAdminSalaryIncrement: 4,
  useOnPremNetworkEngineer: true,
  onPremNetworkEngineerCount: 1,
  onPremNetworkEngineerSalary: 135000,
  onPremNetworkEngineerSalaryIncrement: 4,
  useOnPremStorageAdmin: true,
  onPremStorageAdminCount: 1,
  onPremStorageAdminSalary: 120000,
  onPremStorageAdminSalaryIncrement: 4,
  useOnPremSecurityEngineer: true,
  onPremSecurityEngineerCount: 1,
  onPremSecurityEngineerSalary: 145000,
  onPremSecurityEngineerSalaryIncrement: 4,
  useOnPremDatabaseAdmin: true,
  onPremDatabaseAdminCount: 1,
  onPremDatabaseAdminSalary: 130000,
  onPremDatabaseAdminSalaryIncrement: 4,
  useOnPremDataCenterTech: true,
  onPremDataCenterTechCount: 1,
  onPremDataCenterTechSalary: 85000,
  onPremDataCenterTechSalaryIncrement: 4,
  useCloudDevOpsEngineer: true,
  cloudDevOpsEngineerCount: 2,
  cloudDevOpsEngineerSalary: 155000,
  cloudDevOpsEngineerSalaryIncrement: 4,
  useCloudCloudArchitect: true,
  cloudCloudArchitectCount: 1,
  cloudCloudArchitectSalary: 180000,
  cloudCloudArchitectSalaryIncrement: 4,
  useCloudSiteReliabilityEngineer: true,
  cloudSiteReliabilityEngineerCount: 1,
  cloudSiteReliabilityEngineerSalary: 165000,
  cloudSiteReliabilityEngineerSalaryIncrement: 4,
  useCloudCloudSecurityEngineer: true,
  cloudCloudSecurityEngineerCount: 1,
  cloudCloudSecurityEngineerSalary: 160000,
  cloudCloudSecurityEngineerSalaryIncrement: 4,
  useCloudCloudDatabaseAdmin: false,
  cloudCloudDatabaseAdminCount: 0,
  cloudCloudDatabaseAdminSalary: 0,
  cloudCloudDatabaseAdminSalaryIncrement: 0,
}

export const networkingDefaults: NetworkingValues = {
  useOnPremBandwidth: true,
  onPremBandwidthUsage: 5000,
  onPremBandwidthCostPerGb: 0.02,
  onPremAnnualTrafficGrowth: 15,
  useOnPremCdn: false,
  onPremCdnUsage: 0,
  onPremCdnCostPerGb: 0.04,
  useOnPremCoreSwitch: true,
  onPremCoreSwitchQuantity: 2,
  onPremCoreSwitchUnitCost: 8000,
  onPremCoreSwitchSalvageValue: 10,
  useOnPremAggregationSwitch: true,
  onPremAggregationSwitchQuantity: 4,
  onPremAggregationSwitchUnitCost: 3000,
  onPremAggregationSwitchSalvageValue: 10,
  useOnPremAccessSwitch: true,
  onPremAccessSwitchQuantity: 8,
  onPremAccessSwitchUnitCost: 800,
  onPremAccessSwitchSalvageValue: 10,
  useOnPremCabling: true,
  onPremCablingLength: 500,
  onPremCablingUnitPrice: 2,
  onPremCablingSalvageValue: 10,
  useOnPremQsfp: true,
  onPremQsfpQuantity: 24,
  onPremQsfpUnitCost: 150,
  onPremQsfpSalvageValue: 10,
  useCloudEgress: true,
  cloudEgress: 2,
  cloudEgressGrowthRate: 15,
  cloudEgressCostPerUnit: 0.09,
  useCloudIngress: false,
  cloudIngress: 1,
  cloudIngressGrowthRate: 10,
  cloudIngressCostPerUnit: 0.05,
}

export const softwareDefaults: SoftwareValues = {
  useOnPremVirtualization: true,
  onPremVirtualizationUnitCost: 500,
  onPremVirtualizationLicenses: 4,
  useOnPremOperatingSystem: true,
  onPremOperatingSystemUnitCost: 150,
  onPremOperatingSystemLicenses: 8,
  useOnPremStorage: false,
  onPremStorageUnitCost: 0,
  onPremStorageLicenses: 0,
  useOnPremSoftware: true,
  useOnPremBackupSoftware: true,
  onPremBackupSoftwareUnitCost: 300,
  onPremBackupSoftwareLicenses: 4,
  useOnPremMonitoring: true,
  onPremMonitoringUnitCost: 200,
  onPremMonitoringLicenses: 4,
  useOnPremSecurity: true,
  onPremSecurityUnitCost: 400,
  onPremSecurityLicenses: 4,
  useCloudDatabase: true,
  cloudDatabaseMonthlyCost: 500,
  useCloudOperatingSystem: false,
  cloudOperatingSystemMonthlyCost: 0,
  useCloudAnalytics: true,
  cloudAnalyticsMonthlyCost: 300,
  useCloudTelemetry: true,
  cloudTelemetryMonthlyCost: 200,
  useCloudMonitoring: true,
  cloudMonitoringMonthlyCost: 250,
  useCloudSecurity: true,
  cloudSecurityMonthlyCost: 400,
}

export const storageDefaults: StorageValues = {
  useOnPremHdd: true,
  onPremHddCount: 24,
  onPremHddSizeTb: 8,
  onPremHddRaidFactor: 20,
  onPremHddFailureRate: 2,
  onPremHddUnitCost: 250,
  useOnPremSsd: true,
  onPremSsdCount: 8,
  onPremSsdSizeTb: 4,
  onPremSsdRaidFactor: 20,
  onPremSsdFailureRate: 1,
  onPremSsdUnitCost: 800,
  useOnPremBackup: true,
  onPremBackupStorage: 153.6,
  onPremBackupCostPerUnit: 15,
  useOnPremReplication: false,
  onPremReplicationFactor: 0,
  cloudStorageSize: 150,
  cloudGrowthRate: 20,
  cloudHotTier: 60,
  cloudStandardTier: 30,
  cloudArchiveTier: 10,
  cloudHotStorageCost: 0.021,
  cloudStandardStorageCost: 0.0125,
  cloudArchiveStorageCost: 0.0036,
}

export const securityComplianceDefaults: SecurityComplianceValues = {
  // Certifications
  useCertSoc2: false,
  certSoc2CostType: 'recurring',
  certSoc2Cost: 0,
  useCertIso27001: false,
  certIso27001CostType: 'recurring',
  certIso27001Cost: 0,
  useCertHipaa: false,
  certHipaaCostType: 'recurring',
  certHipaaCost: 0,
  useCertPciDss: false,
  certPciDssCostType: 'recurring',
  certPciDssCost: 0,
  useCertGdpr: false,
  certGdprCostType: 'recurring',
  certGdprCost: 0,
  // Security Features
  useDdosProtection: false,
  ddosProtectionCostType: 'recurring',
  ddosProtectionCost: 0,
  useWaf: false,
  wafCostType: 'recurring',
  wafCost: 0,
  useBotProtection: false,
  botProtectionCostType: 'recurring',
  botProtectionCost: 0,
  useSecurityAudits: false,
  securityAuditsCostType: 'recurring',
  securityAuditsCost: 0,
  usePenetrationTesting: false,
  penetrationTestingCostType: 'recurring',
  penetrationTestingCost: 0,
}

// Combined defaults for backward compatibility
export const defaultValues: CostFormValues = {
  ...generalDefaults,
  ...onPremComputeDefaults,
  ...cloudComputeDefaults,
  ...energyDefaults,
  ...gpuDefaults,
  ...humanResourcesDefaults,
  ...networkingDefaults,
  ...softwareDefaults,
  ...storageDefaults,
  ...securityComplianceDefaults,
}
