import type { Preset } from './types'
import {
  energyDefaults,
  generalDefaults,
  humanResourcesDefaults,
  networkingDefaults,
  securityComplianceDefaults,
  softwareDefaults,
  storageDefaults,
} from '../defaults'

export const aiTrainingPreset: Preset = {
  id: 'ai-training',
  name: 'AI Training Workload',
  description:
    'GPU-intensive AI/ML training workload with high compute requirements',
  icon: '🤖',
  values: {
    ...generalDefaults,
    ...energyDefaults,
    ...humanResourcesDefaults,
    ...networkingDefaults,
    ...softwareDefaults,
    ...storageDefaults,
    ...securityComplianceDefaults,
    // Compute
    useOnPremCpu: true,
    onPremCpuQuantity: 12,
    onPremCpuUnitCost: 4500,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 12,
    onPremMotherboardUnitCost: 1200,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 2048,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 6,
    onPremChassisUnitCost: 5000,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 3,
    onPremRacksUnitCost: 3000,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 8,
    cloudGeneralVmHourlyRate: 0.2,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 12,
    cloudComputeVmHourlyRate: 0.4,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 8,
    cloudMemoryVmHourlyRate: 0.5,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU
    useOnPremTrainingGpu: true,
    onPremTrainingGpuQuantity: 16,
    onPremTrainingGpuUnitCost: 20000,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 8,
    onPremInferenceGpuUnitCost: 8000,
    useCloudTrainingGpu: true,
    cloudTrainingGpuCount: 16,
    cloudTrainingGpuHourlyRate: 4.5,
    cloudTrainingGpuHoursPerMonth: 730,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 8,
    cloudInferenceGpuHourlyRate: 1.2,
    cloudInferenceGpuHoursPerMonth: 730,
  },
}
