import type { Preset } from './types'
import {
  energyDefaults,
  generalDefaults,
  humanResourcesDefaults,
  softwareDefaults,
} from '../defaults'

export const ecommercePlatformPreset: Preset = {
  id: 'ecommerce-platform',
  name: 'E-commerce Platform',
  description:
    'High-traffic e-commerce platform with CDN, security, and compliance needs',
  icon: '🛒',
  values: {
    ...generalDefaults,
    ...energyDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    // Compute
    useOnPremCpu: true,
    onPremCpuQuantity: 6,
    onPremCpuUnitCost: 2800,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 6,
    onPremMotherboardUnitCost: 900,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 768,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 3,
    onPremChassisUnitCost: 3500,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 2,
    onPremRacksUnitCost: 2000,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 16,
    cloudGeneralVmHourlyRate: 0.18,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 6,
    cloudComputeVmHourlyRate: 0.28,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 4,
    cloudMemoryVmHourlyRate: 0.38,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU
    useOnPremTrainingGpu: false,
    onPremTrainingGpuQuantity: 0,
    onPremTrainingGpuUnitCost: 0,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 4,
    onPremInferenceGpuUnitCost: 5000,
    useCloudTrainingGpu: false,
    cloudTrainingGpuCount: 0,
    cloudTrainingGpuHourlyRate: 0,
    cloudTrainingGpuHoursPerMonth: 0,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 4,
    cloudInferenceGpuHourlyRate: 0.65,
    cloudInferenceGpuHoursPerMonth: 730,
    // Networking
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 15000,
    onPremBandwidthCostPerGb: 0.02,
    onPremAnnualTrafficGrowth: 25,
    useOnPremCdn: true,
    onPremCdnUsage: 10000,
    onPremCdnCostPerGb: 0.04,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 2,
    onPremCoreSwitchUnitCost: 8000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 4,
    onPremAggregationSwitchUnitCost: 3000,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 8,
    onPremAccessSwitchUnitCost: 800,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 500,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 24,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 5,
    cloudEgressGrowthRate: 25,
    cloudEgressCostPerUnit: 0.09,
    useCloudIngress: false,
    cloudIngress: 0,
    cloudIngressGrowthRate: 0,
    cloudIngressCostPerUnit: 0,
    // Storage
    useOnPremHdd: true,
    onPremHddCount: 24,
    onPremHddSizeTb: 8,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 2,
    onPremHddUnitCost: 250,
    useOnPremSsd: true,
    onPremSsdCount: 16,
    onPremSsdSizeTb: 4,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 800,
    useOnPremBackup: true,
    onPremBackupStorage: 192,
    onPremBackupCostPerUnit: 15,
    useOnPremReplication: false,
    onPremReplicationFactor: 0,
    cloudStorageSize: 300,
    cloudGrowthRate: 25,
    cloudHotTier: 70,
    cloudStandardTier: 25,
    cloudArchiveTier: 5,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
    // Security & Compliance
    useCertSoc2: true,
    certSoc2CostType: 'recurring',
    certSoc2Cost: 15000,
    useCertIso27001: false,
    certIso27001CostType: 'recurring',
    certIso27001Cost: 0,
    useCertHipaa: false,
    certHipaaCostType: 'recurring',
    certHipaaCost: 0,
    useCertPciDss: true,
    certPciDssCostType: 'recurring',
    certPciDssCost: 25000,
    useCertGdpr: true,
    certGdprCostType: 'recurring',
    certGdprCost: 10000,
    useDdosProtection: true,
    ddosProtectionCostType: 'recurring',
    ddosProtectionCost: 5000,
    useWaf: true,
    wafCostType: 'recurring',
    wafCost: 3000,
    useBotProtection: true,
    botProtectionCostType: 'recurring',
    botProtectionCost: 2000,
    useSecurityAudits: true,
    securityAuditsCostType: 'recurring',
    securityAuditsCost: 8000,
    usePenetrationTesting: true,
    penetrationTestingCostType: 'recurring',
    penetrationTestingCost: 12000,
  },
}