import type { Preset } from './types'
import {
  energyDefaults,
  generalDefaults,
  gpuDefaults,
  humanResourcesDefaults,
  networkingDefaults,
  securityComplianceDefaults,
  softwareDefaults,
} from '../defaults'

export const erpSystemPreset: Preset = {
  id: 'erp-system',
  name: 'ERP System',
  description:
    'Enterprise Resource Planning system with high compute and storage needs',
  icon: '🏢',
  values: {
    ...generalDefaults,
    ...energyDefaults,
    ...gpuDefaults,
    ...humanResourcesDefaults,
    ...networkingDefaults,
    ...softwareDefaults,
    ...securityComplianceDefaults,
    // Compute
    useOnPremCpu: true,
    onPremCpuQuantity: 8,
    onPremCpuUnitCost: 3500,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 8,
    onPremMotherboardUnitCost: 1000,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 1024,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 4,
    onPremChassisUnitCost: 4000,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 2,
    onPremRacksUnitCost: 2500,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 12,
    cloudGeneralVmHourlyRate: 0.2,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 8,
    cloudComputeVmHourlyRate: 0.3,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 4,
    cloudMemoryVmHourlyRate: 0.4,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // Storage
    useOnPremHdd: true,
    onPremHddCount: 48,
    onPremHddSizeTb: 10,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 2,
    onPremHddUnitCost: 300,
    useOnPremSsd: true,
    onPremSsdCount: 12,
    onPremSsdSizeTb: 4,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 800,
    useOnPremBackup: true,
    onPremBackupStorage: 384,
    onPremBackupCostPerUnit: 15,
    useOnPremReplication: true,
    onPremReplicationFactor: 10,
    cloudStorageSize: 500,
    cloudGrowthRate: 15,
    cloudHotTier: 40,
    cloudStandardTier: 40,
    cloudArchiveTier: 20,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
  },
}