import type { Preset } from './types'
import {
  generalDefaults,
  humanResourcesDefaults,
  softwareDefaults,
} from '../defaults'

export const financialServicesPreset: Preset = {
  id: 'financial-services',
  name: 'Financial Services',
  description:
    'Banking and financial services platform with SOC2, PCI-DSS, and high availability',
  icon: '🏦',
  values: {
    ...generalDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    // Compute - High performance for trading and transactions
    useOnPremCpu: true,
    onPremCpuQuantity: 16,
    onPremCpuUnitCost: 4000,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 16,
    onPremMotherboardUnitCost: 1100,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 2048,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 8,
    onPremChassisUnitCost: 5500,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 4,
    onPremRacksUnitCost: 3000,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 20,
    cloudGeneralVmHourlyRate: 0.22,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 12,
    cloudComputeVmHourlyRate: 0.38,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 8,
    cloudMemoryVmHourlyRate: 0.48,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU - Fraud detection and risk analysis
    useOnPremTrainingGpu: true,
    onPremTrainingGpuQuantity: 8,
    onPremTrainingGpuUnitCost: 18000,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 12,
    onPremInferenceGpuUnitCost: 7500,
    useCloudTrainingGpu: true,
    cloudTrainingGpuCount: 8,
    cloudTrainingGpuHourlyRate: 3.8,
    cloudTrainingGpuHoursPerMonth: 730,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 12,
    cloudInferenceGpuHourlyRate: 1.0,
    cloudInferenceGpuHoursPerMonth: 730,
    // Energy - In-house data center with redundant power
    useOnPremPowerConsumption: true,
    onPremPowerRating: 5000,
    onPremLoadFactor: 80,
    onPremElectricityCost: 0.14,
    useOnPremUps: true,
    onPremUpsUnitCost: 15000,
    onPremUpsQuantity: 4,
    onPremUpsBatteryFailureRate: 6,
    onPremUpsBatteryReplacementCost: 3500,
    useOnPremGenerator: true,
    onPremGeneratorUnitCost: 75000,
    onPremGeneratorQuantity: 2,
    onPremGeneratorFuelConsumptionRate: 18,
    onPremGeneratorFuelUnitCost: 4.5,
    onPremGeneratorAnnualUsageHours: 150,
    useOnPremHvac: true,
    onPremHvacUnitCost: 50000,
    onPremHvacQuantity: 3,
    onPremHvacPowerConsumption: 20000,
    onPremHvacLoadFactor: 85,
    onPremHvacTechnicianHourlyRate: 85,
    onPremHvacHoursWorked: 320,
    useOnPremColocation: false,
    onPremColocationMonthlyCost: 0,
    onPremColocationAnnualIncrease: 0,
    // Networking - High bandwidth for trading platforms
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 20000,
    onPremBandwidthCostPerGb: 0.02,
    onPremAnnualTrafficGrowth: 15,
    useOnPremCdn: true,
    onPremCdnUsage: 12000,
    onPremCdnCostPerGb: 0.04,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 4,
    onPremCoreSwitchUnitCost: 15000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 8,
    onPremAggregationSwitchUnitCost: 5000,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 16,
    onPremAccessSwitchUnitCost: 1500,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 800,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 48,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 8,
    cloudEgressGrowthRate: 15,
    cloudEgressCostPerUnit: 0.09,
    useCloudIngress: false,
    cloudIngress: 0,
    cloudIngressGrowthRate: 0,
    cloudIngressCostPerUnit: 0,
    // Storage - High-speed storage for transaction processing
    useOnPremHdd: true,
    onPremHddCount: 60,
    onPremHddSizeTb: 12,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 2,
    onPremHddUnitCost: 350,
    useOnPremSsd: true,
    onPremSsdCount: 32,
    onPremSsdSizeTb: 8,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 1200,
    useOnPremBackup: true,
    onPremBackupStorage: 720,
    onPremBackupCostPerUnit: 15,
    useOnPremReplication: true,
    onPremReplicationFactor: 10,
    cloudStorageSize: 800,
    cloudGrowthRate: 15,
    cloudHotTier: 60,
    cloudStandardTier: 30,
    cloudArchiveTier: 10,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
    // Security & Compliance - Financial industry standards
    useCertSoc2: true,
    certSoc2CostType: 'recurring',
    certSoc2Cost: 35000,
    useCertIso27001: true,
    certIso27001CostType: 'recurring',
    certIso27001Cost: 30000,
    useCertHipaa: false,
    certHipaaCostType: 'recurring',
    certHipaaCost: 0,
    useCertPciDss: true,
    certPciDssCostType: 'recurring',
    certPciDssCost: 40000,
    useCertGdpr: true,
    certGdprCostType: 'recurring',
    certGdprCost: 18000,
    useDdosProtection: true,
    ddosProtectionCostType: 'recurring',
    ddosProtectionCost: 12000,
    useWaf: true,
    wafCostType: 'recurring',
    wafCost: 8000,
    useBotProtection: true,
    botProtectionCostType: 'recurring',
    botProtectionCost: 5000,
    useSecurityAudits: true,
    securityAuditsCostType: 'recurring',
    securityAuditsCost: 50000,
    usePenetrationTesting: true,
    penetrationTestingCostType: 'recurring',
    penetrationTestingCost: 35000,
  },
}
