import type { Preset } from './types'
import {
  energyDefaults,
  generalDefaults,
  humanResourcesDefaults,
  securityComplianceDefaults,
  softwareDefaults,
} from '../defaults'

export const gamingServerPreset: Preset = {
  id: 'gaming-server',
  name: 'Gaming Server',
  description:
    'Low-latency gaming server with GPU acceleration and high bandwidth',
  icon: '🎮',
  values: {
    ...generalDefaults,
    ...energyDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    ...securityComplianceDefaults,
    // Compute
    useOnPremCpu: true,
    onPremCpuQuantity: 6,
    onPremCpuUnitCost: 3000,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 6,
    onPremMotherboardUnitCost: 900,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 512,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 3,
    onPremChassisUnitCost: 3500,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 2,
    onPremRacksUnitCost: 2000,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 10,
    cloudGeneralVmHourlyRate: 0.22,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 6,
    cloudComputeVmHourlyRate: 0.35,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 2,
    cloudMemoryVmHourlyRate: 0.4,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU
    useOnPremTrainingGpu: false,
    onPremTrainingGpuQuantity: 0,
    onPremTrainingGpuUnitCost: 0,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 12,
    onPremInferenceGpuUnitCost: 6000,
    useCloudTrainingGpu: false,
    cloudTrainingGpuCount: 0,
    cloudTrainingGpuHourlyRate: 0,
    cloudTrainingGpuHoursPerMonth: 0,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 12,
    cloudInferenceGpuHourlyRate: 0.8,
    cloudInferenceGpuHoursPerMonth: 730,
    // Networking
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 10000,
    onPremBandwidthCostPerGb: 0.02,
    onPremAnnualTrafficGrowth: 20,
    useOnPremCdn: true,
    onPremCdnUsage: 8000,
    onPremCdnCostPerGb: 0.04,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 2,
    onPremCoreSwitchUnitCost: 10000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 4,
    onPremAggregationSwitchUnitCost: 4000,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 8,
    onPremAccessSwitchUnitCost: 1000,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 400,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 32,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 4,
    cloudEgressGrowthRate: 20,
    cloudEgressCostPerUnit: 0.09,
    useCloudIngress: false,
    cloudIngress: 0,
    cloudIngressGrowthRate: 0,
    cloudIngressCostPerUnit: 0,
    // Storage
    useOnPremHdd: true,
    onPremHddCount: 16,
    onPremHddSizeTb: 6,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 2,
    onPremHddUnitCost: 220,
    useOnPremSsd: true,
    onPremSsdCount: 12,
    onPremSsdSizeTb: 4,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 750,
    useOnPremBackup: true,
    onPremBackupStorage: 76.8,
    onPremBackupCostPerUnit: 15,
    useOnPremReplication: false,
    onPremReplicationFactor: 0,
    cloudStorageSize: 100,
    cloudGrowthRate: 20,
    cloudHotTier: 90,
    cloudStandardTier: 8,
    cloudArchiveTier: 2,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
  },
}
