import type { Preset } from './types'
import {
  generalDefaults,
  humanResourcesDefaults,
  softwareDefaults,
} from '../defaults'

export const governmentCloudPreset: Preset = {
  id: 'government-cloud',
  name: 'Government/Defense',
  description:
    'Government and defense infrastructure with maximum security and compliance requirements',
  icon: '🛡️',
  values: {
    ...generalDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    // Compute - Secure in-house infrastructure
    useOnPremCpu: true,
    onPremCpuQuantity: 20,
    onPremCpuUnitCost: 4500,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 20,
    onPremMotherboardUnitCost: 1200,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 3072,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 10,
    onPremChassisUnitCost: 6000,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 5,
    onPremRacksUnitCost: 3500,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 15,
    cloudGeneralVmHourlyRate: 0.25,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 10,
    cloudComputeVmHourlyRate: 0.42,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 10,
    cloudMemoryVmHourlyRate: 0.52,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU - Data analysis and intelligence
    useOnPremTrainingGpu: true,
    onPremTrainingGpuQuantity: 12,
    onPremTrainingGpuUnitCost: 22000,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 16,
    onPremInferenceGpuUnitCost: 9000,
    useCloudTrainingGpu: true,
    cloudTrainingGpuCount: 12,
    cloudTrainingGpuHourlyRate: 4.2,
    cloudTrainingGpuHoursPerMonth: 730,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 16,
    cloudInferenceGpuHourlyRate: 1.3,
    cloudInferenceGpuHoursPerMonth: 730,
    // Energy - Hardened facility with full redundancy
    useOnPremPowerConsumption: true,
    onPremPowerRating: 7000,
    onPremLoadFactor: 85,
    onPremElectricityCost: 0.14,
    useOnPremUps: true,
    onPremUpsUnitCost: 25000,
    onPremUpsQuantity: 5,
    onPremUpsBatteryFailureRate: 5,
    onPremUpsBatteryReplacementCost: 5000,
    useOnPremGenerator: true,
    onPremGeneratorUnitCost: 125000,
    onPremGeneratorQuantity: 3,
    onPremGeneratorFuelConsumptionRate: 25,
    onPremGeneratorFuelUnitCost: 4.5,
    onPremGeneratorAnnualUsageHours: 250,
    useOnPremHvac: true,
    onPremHvacUnitCost: 75000,
    onPremHvacQuantity: 4,
    onPremHvacPowerConsumption: 30000,
    onPremHvacLoadFactor: 90,
    onPremHvacTechnicianHourlyRate: 95,
    onPremHvacHoursWorked: 480,
    useOnPremColocation: false,
    onPremColocationMonthlyCost: 0,
    onPremColocationAnnualIncrease: 0,
    // Networking - Isolated and secure networks
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 12000,
    onPremBandwidthCostPerGb: 0.02,
    onPremAnnualTrafficGrowth: 10,
    useOnPremCdn: false,
    onPremCdnUsage: 0,
    onPremCdnCostPerGb: 0,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 6,
    onPremCoreSwitchUnitCost: 18000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 12,
    onPremAggregationSwitchUnitCost: 6000,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 20,
    onPremAccessSwitchUnitCost: 2000,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 1000,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 64,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 5,
    cloudEgressGrowthRate: 10,
    cloudEgressCostPerUnit: 0.09,
    useCloudIngress: false,
    cloudIngress: 0,
    cloudIngressGrowthRate: 0,
    cloudIngressCostPerUnit: 0,
    // Storage - Classified data storage with triple redundancy
    useOnPremHdd: true,
    onPremHddCount: 80,
    onPremHddSizeTb: 16,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 2,
    onPremHddUnitCost: 400,
    useOnPremSsd: true,
    onPremSsdCount: 40,
    onPremSsdSizeTb: 8,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 1400,
    useOnPremBackup: true,
    onPremBackupStorage: 1280,
    onPremBackupCostPerUnit: 15,
    useOnPremReplication: true,
    onPremReplicationFactor: 10,
    cloudStorageSize: 1000,
    cloudGrowthRate: 10,
    cloudHotTier: 45,
    cloudStandardTier: 40,
    cloudArchiveTier: 15,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
    // Security & Compliance - Maximum security requirements
    useCertSoc2: true,
    certSoc2CostType: 'recurring',
    certSoc2Cost: 45000,
    useCertIso27001: true,
    certIso27001CostType: 'recurring',
    certIso27001Cost: 40000,
    useCertHipaa: false,
    certHipaaCostType: 'recurring',
    certHipaaCost: 0,
    useCertPciDss: false,
    certPciDssCostType: 'recurring',
    certPciDssCost: 0,
    useCertGdpr: true,
    certGdprCostType: 'recurring',
    certGdprCost: 20000,
    useDdosProtection: true,
    ddosProtectionCostType: 'recurring',
    ddosProtectionCost: 15000,
    useWaf: true,
    wafCostType: 'recurring',
    wafCost: 10000,
    useBotProtection: true,
    botProtectionCostType: 'recurring',
    botProtectionCost: 8000,
    useSecurityAudits: true,
    securityAuditsCostType: 'recurring',
    securityAuditsCost: 75000,
    usePenetrationTesting: true,
    penetrationTestingCostType: 'recurring',
    penetrationTestingCost: 50000,
  },
}
