import type { Preset } from './types'
import {
  generalDefaults,
  humanResourcesDefaults,
  softwareDefaults,
} from '../defaults'

export const healthcarePlatformPreset: Preset = {
  id: 'healthcare-platform',
  name: 'Healthcare Platform',
  description:
    'HIPAA-compliant healthcare platform with strict security and data protection',
  icon: '🏥',
  values: {
    ...generalDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    // Compute
    useOnPremCpu: true,
    onPremCpuQuantity: 10,
    onPremCpuUnitCost: 3200,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 10,
    onPremMotherboardUnitCost: 950,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 1536,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 5,
    onPremChassisUnitCost: 4500,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 3,
    onPremRacksUnitCost: 2500,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 10,
    cloudGeneralVmHourlyRate: 0.18,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 8,
    cloudComputeVmHourlyRate: 0.32,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 6,
    cloudMemoryVmHourlyRate: 0.42,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU - AI for medical imaging
    useOnPremTrainingGpu: false,
    onPremTrainingGpuQuantity: 0,
    onPremTrainingGpuUnitCost: 0,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 6,
    onPremInferenceGpuUnitCost: 7000,
    useCloudTrainingGpu: false,
    cloudTrainingGpuCount: 0,
    cloudTrainingGpuHourlyRate: 0,
    cloudTrainingGpuHoursPerMonth: 0,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 6,
    cloudInferenceGpuHourlyRate: 0.9,
    cloudInferenceGpuHoursPerMonth: 730,
    // Energy - In-house infrastructure with full backup
    useOnPremPowerConsumption: true,
    onPremPowerRating: 3500,
    onPremLoadFactor: 75,
    onPremElectricityCost: 0.14,
    useOnPremUps: true,
    onPremUpsUnitCost: 8000,
    onPremUpsQuantity: 3,
    onPremUpsBatteryFailureRate: 8,
    onPremUpsBatteryReplacementCost: 2500,
    useOnPremGenerator: true,
    onPremGeneratorUnitCost: 45000,
    onPremGeneratorQuantity: 2,
    onPremGeneratorFuelConsumptionRate: 12,
    onPremGeneratorFuelUnitCost: 4.5,
    onPremGeneratorAnnualUsageHours: 200,
    useOnPremHvac: true,
    onPremHvacUnitCost: 35000,
    onPremHvacQuantity: 2,
    onPremHvacPowerConsumption: 15000,
    onPremHvacLoadFactor: 80,
    onPremHvacTechnicianHourlyRate: 75,
    onPremHvacHoursWorked: 240,
    useOnPremColocation: false,
    onPremColocationMonthlyCost: 0,
    onPremColocationAnnualIncrease: 0,
    // Networking
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 8000,
    onPremBandwidthCostPerGb: 0.02,
    onPremAnnualTrafficGrowth: 18,
    useOnPremCdn: false,
    onPremCdnUsage: 0,
    onPremCdnCostPerGb: 0,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 2,
    onPremCoreSwitchUnitCost: 12000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 4,
    onPremAggregationSwitchUnitCost: 4000,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 10,
    onPremAccessSwitchUnitCost: 1200,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 600,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 32,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 3,
    cloudEgressGrowthRate: 18,
    cloudEgressCostPerUnit: 0.09,
    useCloudIngress: false,
    cloudIngress: 0,
    cloudIngressGrowthRate: 0,
    cloudIngressCostPerUnit: 0,
    // Storage - High redundancy for patient data
    useOnPremHdd: true,
    onPremHddCount: 40,
    onPremHddSizeTb: 10,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 2,
    onPremHddUnitCost: 300,
    useOnPremSsd: true,
    onPremSsdCount: 16,
    onPremSsdSizeTb: 4,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 850,
    useOnPremBackup: true,
    onPremBackupStorage: 400,
    onPremBackupCostPerUnit: 15,
    useOnPremReplication: true,
    onPremReplicationFactor: 10,
    cloudStorageSize: 450,
    cloudGrowthRate: 18,
    cloudHotTier: 50,
    cloudStandardTier: 35,
    cloudArchiveTier: 15,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
    // Security & Compliance - Full HIPAA compliance
    useCertSoc2: true,
    certSoc2CostType: 'recurring',
    certSoc2Cost: 20000,
    useCertIso27001: true,
    certIso27001CostType: 'recurring',
    certIso27001Cost: 25000,
    useCertHipaa: true,
    certHipaaCostType: 'recurring',
    certHipaaCost: 50000,
    useCertPciDss: false,
    certPciDssCostType: 'recurring',
    certPciDssCost: 0,
    useCertGdpr: true,
    certGdprCostType: 'recurring',
    certGdprCost: 15000,
    useDdosProtection: true,
    ddosProtectionCostType: 'recurring',
    ddosProtectionCost: 8000,
    useWaf: true,
    wafCostType: 'recurring',
    wafCost: 5000,
    useBotProtection: true,
    botProtectionCostType: 'recurring',
    botProtectionCost: 3000,
    useSecurityAudits: true,
    securityAuditsCostType: 'recurring',
    securityAuditsCost: 35000,
    usePenetrationTesting: true,
    penetrationTestingCostType: 'recurring',
    penetrationTestingCost: 25000,
  },
}
