import type { Preset } from './types'
import {
  generalDefaults,
  humanResourcesDefaults,
  softwareDefaults,
} from '../defaults'

export const mediaStreamingPreset: Preset = {
  id: 'media-streaming',
  name: 'Media & Streaming',
  description:
    'Video streaming platform with high bandwidth, CDN, and content delivery requirements',
  icon: '📺',
  values: {
    ...generalDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    // Compute - Video encoding and transcoding
    useOnPremCpu: true,
    onPremCpuQuantity: 14,
    onPremCpuUnitCost: 3800,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 14,
    onPremMotherboardUnitCost: 1050,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 1280,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 7,
    onPremChassisUnitCost: 4800,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 4,
    onPremRacksUnitCost: 2800,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 24,
    cloudGeneralVmHourlyRate: 0.19,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 16,
    cloudComputeVmHourlyRate: 0.33,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 8,
    cloudMemoryVmHourlyRate: 0.43,
    cloudMemoryVmHoursPerMonth: 730,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU - Video encoding and AI recommendations
    useOnPremTrainingGpu: true,
    onPremTrainingGpuQuantity: 6,
    onPremTrainingGpuUnitCost: 16000,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 20,
    onPremInferenceGpuUnitCost: 6500,
    useCloudTrainingGpu: true,
    cloudTrainingGpuCount: 6,
    cloudTrainingGpuHourlyRate: 3.2,
    cloudTrainingGpuHoursPerMonth: 730,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 20,
    cloudInferenceGpuHourlyRate: 0.85,
    cloudInferenceGpuHoursPerMonth: 730,
    // Energy - In-house with reliable power
    useOnPremPowerConsumption: true,
    onPremPowerRating: 4200,
    onPremLoadFactor: 78,
    onPremElectricityCost: 0.14,
    useOnPremUps: true,
    onPremUpsUnitCost: 12000,
    onPremUpsQuantity: 4,
    onPremUpsBatteryFailureRate: 7,
    onPremUpsBatteryReplacementCost: 3000,
    useOnPremGenerator: true,
    onPremGeneratorUnitCost: 60000,
    onPremGeneratorQuantity: 2,
    onPremGeneratorFuelConsumptionRate: 15,
    onPremGeneratorFuelUnitCost: 4.5,
    onPremGeneratorAnnualUsageHours: 180,
    useOnPremHvac: true,
    onPremHvacUnitCost: 42000,
    onPremHvacQuantity: 3,
    onPremHvacPowerConsumption: 18000,
    onPremHvacLoadFactor: 82,
    onPremHvacTechnicianHourlyRate: 78,
    onPremHvacHoursWorked: 280,
    useOnPremColocation: false,
    onPremColocationMonthlyCost: 0,
    onPremColocationAnnualIncrease: 0,
    // Networking - Massive bandwidth for content delivery
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 50000,
    onPremBandwidthCostPerGb: 0.015,
    onPremAnnualTrafficGrowth: 35,
    useOnPremCdn: true,
    onPremCdnUsage: 40000,
    onPremCdnCostPerGb: 0.035,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 4,
    onPremCoreSwitchUnitCost: 14000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 8,
    onPremAggregationSwitchUnitCost: 4500,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 14,
    onPremAccessSwitchUnitCost: 1300,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 750,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 56,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 20,
    cloudEgressGrowthRate: 35,
    cloudEgressCostPerUnit: 0.08,
    useCloudIngress: true,
    cloudIngress: 8,
    cloudIngressGrowthRate: 30,
    cloudIngressCostPerUnit: 0.04,
    // Storage - Massive storage for video content
    useOnPremHdd: true,
    onPremHddCount: 120,
    onPremHddSizeTb: 18,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 3,
    onPremHddUnitCost: 450,
    useOnPremSsd: true,
    onPremSsdCount: 24,
    onPremSsdSizeTb: 8,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 1300,
    useOnPremBackup: true,
    onPremBackupStorage: 2160,
    onPremBackupCostPerUnit: 12,
    useOnPremReplication: false,
    onPremReplicationFactor: 0,
    cloudStorageSize: 2500,
    cloudGrowthRate: 35,
    cloudHotTier: 30,
    cloudStandardTier: 50,
    cloudArchiveTier: 20,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
    // Security & Compliance - Content protection and DRM
    useCertSoc2: true,
    certSoc2CostType: 'recurring',
    certSoc2Cost: 18000,
    useCertIso27001: false,
    certIso27001CostType: 'recurring',
    certIso27001Cost: 0,
    useCertHipaa: false,
    certHipaaCostType: 'recurring',
    certHipaaCost: 0,
    useCertPciDss: true,
    certPciDssCostType: 'recurring',
    certPciDssCost: 22000,
    useCertGdpr: true,
    certGdprCostType: 'recurring',
    certGdprCost: 12000,
    useDdosProtection: true,
    ddosProtectionCostType: 'recurring',
    ddosProtectionCost: 10000,
    useWaf: true,
    wafCostType: 'recurring',
    wafCost: 6000,
    useBotProtection: true,
    botProtectionCostType: 'recurring',
    botProtectionCost: 4500,
    useSecurityAudits: true,
    securityAuditsCostType: 'recurring',
    securityAuditsCost: 15000,
    usePenetrationTesting: true,
    penetrationTestingCostType: 'recurring',
    penetrationTestingCost: 18000,
  },
}
