import type { Preset } from './types'
import {
  generalDefaults,
  humanResourcesDefaults,
  softwareDefaults,
} from '../defaults'

export const researchUniversityPreset: Preset = {
  id: 'research-university',
  name: 'Research & Education',
  description:
    'University research infrastructure with HPC clusters and data analytics',
  icon: '🎓',
  values: {
    ...generalDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    // Compute - Research and simulation workloads
    useOnPremCpu: true,
    onPremCpuQuantity: 24,
    onPremCpuUnitCost: 3600,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 24,
    onPremMotherboardUnitCost: 950,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 3584,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 12,
    onPremChassisUnitCost: 4200,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 6,
    onPremRacksUnitCost: 2600,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 12,
    cloudGeneralVmHourlyRate: 0.16,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 20,
    cloudComputeVmHourlyRate: 0.36,
    cloudComputeVmHoursPerMonth: 500,
    useCloudMemoryVm: true,
    cloudMemoryVmCount: 12,
    cloudMemoryVmHourlyRate: 0.46,
    cloudMemoryVmHoursPerMonth: 500,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU - Scientific computing and ML research
    useOnPremTrainingGpu: true,
    onPremTrainingGpuQuantity: 32,
    onPremTrainingGpuUnitCost: 18000,
    useOnPremInferenceGpu: true,
    onPremInferenceGpuQuantity: 16,
    onPremInferenceGpuUnitCost: 7000,
    useCloudTrainingGpu: true,
    cloudTrainingGpuCount: 20,
    cloudTrainingGpuHourlyRate: 3.6,
    cloudTrainingGpuHoursPerMonth: 400,
    useCloudInferenceGpu: true,
    cloudInferenceGpuCount: 10,
    cloudInferenceGpuHourlyRate: 0.95,
    cloudInferenceGpuHoursPerMonth: 400,
    // Energy - Campus data center
    useOnPremPowerConsumption: true,
    onPremPowerRating: 6500,
    onPremLoadFactor: 70,
    onPremElectricityCost: 0.12,
    useOnPremUps: true,
    onPremUpsUnitCost: 18000,
    onPremUpsQuantity: 4,
    onPremUpsBatteryFailureRate: 8,
    onPremUpsBatteryReplacementCost: 4000,
    useOnPremGenerator: true,
    onPremGeneratorUnitCost: 85000,
    onPremGeneratorQuantity: 2,
    onPremGeneratorFuelConsumptionRate: 20,
    onPremGeneratorFuelUnitCost: 4.2,
    onPremGeneratorAnnualUsageHours: 120,
    useOnPremHvac: true,
    onPremHvacUnitCost: 55000,
    onPremHvacQuantity: 3,
    onPremHvacPowerConsumption: 22000,
    onPremHvacLoadFactor: 75,
    onPremHvacTechnicianHourlyRate: 72,
    onPremHvacHoursWorked: 300,
    useOnPremColocation: false,
    onPremColocationMonthlyCost: 0,
    onPremColocationAnnualIncrease: 0,
    // Networking - Campus network and research collaboration
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 18000,
    onPremBandwidthCostPerGb: 0.01,
    onPremAnnualTrafficGrowth: 22,
    useOnPremCdn: false,
    onPremCdnUsage: 0,
    onPremCdnCostPerGb: 0,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 3,
    onPremCoreSwitchUnitCost: 16000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 8,
    onPremAggregationSwitchUnitCost: 5500,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 18,
    onPremAccessSwitchUnitCost: 1800,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 1200,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 72,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 6,
    cloudEgressGrowthRate: 22,
    cloudEgressCostPerUnit: 0.09,
    useCloudIngress: true,
    cloudIngress: 4,
    cloudIngressGrowthRate: 20,
    cloudIngressCostPerUnit: 0.05,
    // Storage - Research data and academic archives
    useOnPremHdd: true,
    onPremHddCount: 200,
    onPremHddSizeTb: 20,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 3,
    onPremHddUnitCost: 480,
    useOnPremSsd: true,
    onPremSsdCount: 48,
    onPremSsdSizeTb: 8,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 1350,
    useOnPremBackup: true,
    onPremBackupStorage: 3200,
    onPremBackupCostPerUnit: 10,
    useOnPremReplication: true,
    onPremReplicationFactor: 10,
    cloudStorageSize: 1500,
    cloudGrowthRate: 25,
    cloudHotTier: 25,
    cloudStandardTier: 45,
    cloudArchiveTier: 30,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
    // Security & Compliance - Research data protection
    useCertSoc2: true,
    certSoc2CostType: 'recurring',
    certSoc2Cost: 16000,
    useCertIso27001: true,
    certIso27001CostType: 'recurring',
    certIso27001Cost: 20000,
    useCertHipaa: false,
    certHipaaCostType: 'recurring',
    certHipaaCost: 0,
    useCertPciDss: false,
    certPciDssCostType: 'recurring',
    certPciDssCost: 0,
    useCertGdpr: true,
    certGdprCostType: 'recurring',
    certGdprCost: 14000,
    useDdosProtection: true,
    ddosProtectionCostType: 'recurring',
    ddosProtectionCost: 6000,
    useWaf: true,
    wafCostType: 'recurring',
    wafCost: 4000,
    useBotProtection: false,
    botProtectionCostType: 'recurring',
    botProtectionCost: 0,
    useSecurityAudits: true,
    securityAuditsCostType: 'recurring',
    securityAuditsCost: 22000,
    usePenetrationTesting: true,
    penetrationTestingCostType: 'recurring',
    penetrationTestingCost: 15000,
  },
}
