import type { Preset } from './types'
import {
  energyDefaults,
  generalDefaults,
  humanResourcesDefaults,
  securityComplianceDefaults,
  softwareDefaults,
} from '../defaults'

export const webSaasPreset: Preset = {
  id: 'web-saas',
  name: 'Web SaaS Application',
  description: 'Lightweight SaaS application with moderate traffic and storage',
  icon: '☁️',
  values: {
    ...generalDefaults,
    ...energyDefaults,
    ...humanResourcesDefaults,
    ...softwareDefaults,
    ...securityComplianceDefaults,
    // Compute
    useOnPremCpu: true,
    onPremCpuQuantity: 2,
    onPremCpuUnitCost: 2000,
    onPremCpuSalvageValue: 10,
    useOnPremMotherboard: true,
    onPremMotherboardQuantity: 2,
    onPremMotherboardUnitCost: 600,
    onPremMotherboardSalvageValue: 10,
    useOnPremMemory: true,
    onPremMemoryCapacityGb: 256,
    onPremMemoryCostPerGb: 8,
    onPremMemorySalvageValue: 10,
    useOnPremChassis: true,
    onPremChassisQuantity: 1,
    onPremChassisUnitCost: 2000,
    onPremChassisSalvageValue: 10,
    useOnPremRacks: true,
    onPremRacksQuantity: 1,
    onPremRacksUnitCost: 1500,
    onPremRacksSalvageValue: 10,
    useCloudGeneralVm: true,
    cloudGeneralVmCount: 6,
    cloudGeneralVmHourlyRate: 0.12,
    cloudGeneralVmHoursPerMonth: 730,
    useCloudComputeVm: true,
    cloudComputeVmCount: 2,
    cloudComputeVmHourlyRate: 0.2,
    cloudComputeVmHoursPerMonth: 730,
    useCloudMemoryVm: false,
    cloudMemoryVmCount: 0,
    cloudMemoryVmHourlyRate: 0,
    cloudMemoryVmHoursPerMonth: 0,
    useCloudStorageVm: false,
    cloudStorageVmCount: 0,
    cloudStorageVmHourlyRate: 0,
    cloudStorageVmHoursPerMonth: 0,
    // GPU
    useOnPremTrainingGpu: false,
    onPremTrainingGpuQuantity: 0,
    onPremTrainingGpuUnitCost: 0,
    useOnPremInferenceGpu: false,
    onPremInferenceGpuQuantity: 0,
    onPremInferenceGpuUnitCost: 0,
    useCloudTrainingGpu: false,
    cloudTrainingGpuCount: 0,
    cloudTrainingGpuHourlyRate: 0,
    cloudTrainingGpuHoursPerMonth: 0,
    useCloudInferenceGpu: false,
    cloudInferenceGpuCount: 0,
    cloudInferenceGpuHourlyRate: 0,
    cloudInferenceGpuHoursPerMonth: 0,
    // Networking
    useOnPremBandwidth: true,
    onPremBandwidthUsage: 2000,
    onPremBandwidthCostPerGb: 0.02,
    onPremAnnualTrafficGrowth: 30,
    useOnPremCdn: true,
    onPremCdnUsage: 1500,
    onPremCdnCostPerGb: 0.04,
    useOnPremCoreSwitch: true,
    onPremCoreSwitchQuantity: 1,
    onPremCoreSwitchUnitCost: 5000,
    onPremCoreSwitchSalvageValue: 10,
    useOnPremAggregationSwitch: true,
    onPremAggregationSwitchQuantity: 2,
    onPremAggregationSwitchUnitCost: 2000,
    onPremAggregationSwitchSalvageValue: 10,
    useOnPremAccessSwitch: true,
    onPremAccessSwitchQuantity: 4,
    onPremAccessSwitchUnitCost: 500,
    onPremAccessSwitchSalvageValue: 10,
    useOnPremCabling: true,
    onPremCablingLength: 200,
    onPremCablingUnitPrice: 2,
    onPremCablingSalvageValue: 10,
    useOnPremQsfp: true,
    onPremQsfpQuantity: 12,
    onPremQsfpUnitCost: 150,
    onPremQsfpSalvageValue: 10,
    useCloudEgress: true,
    cloudEgress: 1,
    cloudEgressGrowthRate: 30,
    cloudEgressCostPerUnit: 0.09,
    useCloudIngress: false,
    cloudIngress: 0,
    cloudIngressGrowthRate: 0,
    cloudIngressCostPerUnit: 0,
    // Storage
    useOnPremHdd: true,
    onPremHddCount: 12,
    onPremHddSizeTb: 4,
    onPremHddRaidFactor: 20,
    onPremHddFailureRate: 2,
    onPremHddUnitCost: 200,
    useOnPremSsd: true,
    onPremSsdCount: 4,
    onPremSsdSizeTb: 2,
    onPremSsdRaidFactor: 20,
    onPremSsdFailureRate: 1,
    onPremSsdUnitCost: 500,
    useOnPremBackup: true,
    onPremBackupStorage: 38.4,
    onPremBackupCostPerUnit: 15,
    useOnPremReplication: false,
    onPremReplicationFactor: 0,
    cloudStorageSize: 50,
    cloudGrowthRate: 30,
    cloudHotTier: 80,
    cloudStandardTier: 15,
    cloudArchiveTier: 5,
    cloudHotStorageCost: 0.021,
    cloudStandardStorageCost: 0.0125,
    cloudArchiveStorageCost: 0.0036,
  },
}
